// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: apiKey.proto

package nan0

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ApiKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncKey  []byte `protobuf:"bytes,1,opt,name=encKey,proto3" json:"encKey,omitempty"`
	HmacKey []byte `protobuf:"bytes,2,opt,name=hmacKey,proto3" json:"hmacKey,omitempty"`
}

func (x *ApiKey) Reset() {
	*x = ApiKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apiKey_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKey) ProtoMessage() {}

func (x *ApiKey) ProtoReflect() protoreflect.Message {
	mi := &file_apiKey_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKey.ProtoReflect.Descriptor instead.
func (*ApiKey) Descriptor() ([]byte, []int) {
	return file_apiKey_proto_rawDescGZIP(), []int{0}
}

func (x *ApiKey) GetEncKey() []byte {
	if x != nil {
		return x.EncKey
	}
	return nil
}

func (x *ApiKey) GetHmacKey() []byte {
	if x != nil {
		return x.HmacKey
	}
	return nil
}

var File_apiKey_proto protoreflect.FileDescriptor

var file_apiKey_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6e, 0x61, 0x6e, 0x30, 0x22, 0x3a, 0x0a, 0x06, 0x41, 0x70, 0x69, 0x4b, 0x65, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x65, 0x6e, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6d, 0x61, 0x63, 0x4b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x68, 0x6d, 0x61, 0x63, 0x4b, 0x65, 0x79,
	0x42, 0x3a, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x6f, 0x64, 0x65, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x6a, 0x6e, 0x61, 0x6e, 0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x05, 0x6a,
	0x6e, 0x61, 0x6e, 0x30, 0x5a, 0x16, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x79, 0x6f, 0x6d, 0x69, 0x6a, 0x69, 0x2f, 0x6e, 0x61, 0x6e, 0x30, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apiKey_proto_rawDescOnce sync.Once
	file_apiKey_proto_rawDescData = file_apiKey_proto_rawDesc
)

func file_apiKey_proto_rawDescGZIP() []byte {
	file_apiKey_proto_rawDescOnce.Do(func() {
		file_apiKey_proto_rawDescData = protoimpl.X.CompressGZIP(file_apiKey_proto_rawDescData)
	})
	return file_apiKey_proto_rawDescData
}

var file_apiKey_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_apiKey_proto_goTypes = []interface{}{
	(*ApiKey)(nil), // 0: nan0.ApiKey
}
var file_apiKey_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apiKey_proto_init() }
func file_apiKey_proto_init() {
	if File_apiKey_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apiKey_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apiKey_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiKey_proto_goTypes,
		DependencyIndexes: file_apiKey_proto_depIdxs,
		MessageInfos:      file_apiKey_proto_msgTypes,
	}.Build()
	File_apiKey_proto = out.File
	file_apiKey_proto_rawDesc = nil
	file_apiKey_proto_goTypes = nil
	file_apiKey_proto_depIdxs = nil
}
