// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nanoservice_descriptor.proto

package service_discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Nanoservice struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	TimeToLiveInMS       int64    `protobuf:"varint,2,opt,name=timeToLiveInMS,proto3" json:"timeToLiveInMS,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ServiceName          string   `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceType          string   `protobuf:"bytes,6,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nanoservice) Reset()         { *m = Nanoservice{} }
func (m *Nanoservice) String() string { return proto.CompactTextString(m) }
func (*Nanoservice) ProtoMessage()    {}
func (*Nanoservice) Descriptor() ([]byte, []int) {
	return fileDescriptor_nanoservice_descriptor_f32d9dafe877c742, []int{0}
}
func (m *Nanoservice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nanoservice.Unmarshal(m, b)
}
func (m *Nanoservice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nanoservice.Marshal(b, m, deterministic)
}
func (dst *Nanoservice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nanoservice.Merge(dst, src)
}
func (m *Nanoservice) XXX_Size() int {
	return xxx_messageInfo_Nanoservice.Size(m)
}
func (m *Nanoservice) XXX_DiscardUnknown() {
	xxx_messageInfo_Nanoservice.DiscardUnknown(m)
}

var xxx_messageInfo_Nanoservice proto.InternalMessageInfo

func (m *Nanoservice) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Nanoservice) GetTimeToLiveInMS() int64 {
	if m != nil {
		return m.TimeToLiveInMS
	}
	return 0
}

func (m *Nanoservice) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Nanoservice) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Nanoservice) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Nanoservice) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type ServiceListRequest struct {
	ServiceType          string         `protobuf:"bytes,1,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Services             []*Nanoservice `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ServiceListRequest) Reset()         { *m = ServiceListRequest{} }
func (m *ServiceListRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceListRequest) ProtoMessage()    {}
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_nanoservice_descriptor_f32d9dafe877c742, []int{1}
}
func (m *ServiceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListRequest.Unmarshal(m, b)
}
func (m *ServiceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListRequest.Marshal(b, m, deterministic)
}
func (dst *ServiceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListRequest.Merge(dst, src)
}
func (m *ServiceListRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceListRequest.Size(m)
}
func (m *ServiceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListRequest proto.InternalMessageInfo

func (m *ServiceListRequest) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ServiceListRequest) GetServices() []*Nanoservice {
	if m != nil {
		return m.Services
	}
	return nil
}

type KeepAlive struct {
	IsAlive              bool     `protobuf:"varint,1,opt,name=isAlive,proto3" json:"isAlive,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeepAlive) Reset()         { *m = KeepAlive{} }
func (m *KeepAlive) String() string { return proto.CompactTextString(m) }
func (*KeepAlive) ProtoMessage()    {}
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return fileDescriptor_nanoservice_descriptor_f32d9dafe877c742, []int{2}
}
func (m *KeepAlive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAlive.Unmarshal(m, b)
}
func (m *KeepAlive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAlive.Marshal(b, m, deterministic)
}
func (dst *KeepAlive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAlive.Merge(dst, src)
}
func (m *KeepAlive) XXX_Size() int {
	return xxx_messageInfo_KeepAlive.Size(m)
}
func (m *KeepAlive) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAlive.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAlive proto.InternalMessageInfo

func (m *KeepAlive) GetIsAlive() bool {
	if m != nil {
		return m.IsAlive
	}
	return false
}

func init() {
	proto.RegisterType((*Nanoservice)(nil), "service_discovery.Nanoservice")
	proto.RegisterType((*ServiceListRequest)(nil), "service_discovery.ServiceListRequest")
	proto.RegisterType((*KeepAlive)(nil), "service_discovery.KeepAlive")
}

func init() {
	proto.RegisterFile("nanoservice_descriptor.proto", fileDescriptor_nanoservice_descriptor_f32d9dafe877c742)
}

var fileDescriptor_nanoservice_descriptor_f32d9dafe877c742 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0x27, 0xeb, 0x36, 0xdb, 0x57, 0x10, 0x7c, 0x5e, 0x82, 0x0c, 0x09, 0x05, 0xa5, 0xa7, 0x1e,
	0xf4, 0xe6, 0x4d, 0x6f, 0xe2, 0xdc, 0x21, 0xeb, 0xc9, 0x8b, 0xd4, 0xfa, 0xc0, 0x80, 0x6d, 0x62,
	0x12, 0x0b, 0xfb, 0x84, 0x7e, 0x2d, 0x31, 0xce, 0xae, 0xb6, 0xb7, 0xdf, 0x5f, 0x12, 0x7e, 0x0f,
	0x56, 0x6d, 0xd5, 0x6a, 0x47, 0xb6, 0x53, 0x35, 0x3d, 0xbf, 0x92, 0xab, 0xad, 0x32, 0x5e, 0xdb,
	0xc2, 0x58, 0xed, 0x35, 0x9e, 0xf4, 0x8e, 0x72, 0xb5, 0xee, 0xc8, 0xee, 0xb2, 0x2f, 0x06, 0xe9,
	0xe6, 0xd0, 0x41, 0x84, 0xb9, 0xd1, 0xd6, 0x73, 0x26, 0x58, 0xbe, 0x90, 0x01, 0xe3, 0x25, 0x1c,
	0x7b, 0xd5, 0x50, 0xa9, 0xd7, 0xaa, 0xa3, 0xfb, 0xf6, 0x71, 0xcb, 0x67, 0x82, 0xe5, 0x91, 0x1c,
	0xa9, 0xb8, 0x82, 0xc4, 0xf9, 0xca, 0xfa, 0x52, 0x35, 0xc4, 0xa3, 0x10, 0x39, 0x08, 0x78, 0x06,
	0xf1, 0x9b, 0x76, 0x7e, 0x53, 0x35, 0xc4, 0xe7, 0x82, 0xe5, 0x89, 0xec, 0x39, 0x0a, 0x48, 0xf7,
	0x1f, 0x08, 0xf6, 0x22, 0xd8, 0x43, 0x69, 0x90, 0x28, 0x77, 0x86, 0xf8, 0xf2, 0x5f, 0xe2, 0x47,
	0xca, 0x2c, 0xe0, 0xf6, 0x97, 0xae, 0x95, 0xf3, 0x92, 0x3e, 0x3e, 0xc9, 0xf9, 0x71, 0x8f, 0x4d,
	0x7a, 0x78, 0x03, 0xf1, 0x9e, 0x3a, 0x3e, 0x13, 0x51, 0x9e, 0x5e, 0x9d, 0x17, 0x93, 0x9d, 0x8a,
	0xc1, 0x46, 0xb2, 0xcf, 0x67, 0x17, 0x90, 0x3c, 0x10, 0x99, 0xdb, 0x77, 0xd5, 0x11, 0x72, 0x38,
	0x52, 0x2e, 0xc0, 0xf0, 0x4c, 0x2c, 0xff, 0xe8, 0xdd, 0xe9, 0xd3, 0x74, 0xf9, 0x97, 0x65, 0xb8,
	0xc9, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x06, 0x8a, 0x1e, 0xb3, 0x01, 0x00, 0x00,
}
