// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package nan0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	TimeToLiveInMS       int64    `protobuf:"varint,2,opt,name=timeToLiveInMS,proto3" json:"timeToLiveInMS,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ServiceName          string   `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceType          string   `protobuf:"bytes,6,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ee3d25153dcd3644, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetTimeToLiveInMS() int64 {
	if m != nil {
		return m.TimeToLiveInMS
	}
	return 0
}

func (m *Service) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Service) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type ServiceList struct {
	ServiceType          string     `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ServicesAvailable    []*Service `protobuf:"bytes,3,rep,name=servicesAvailable,proto3" json:"servicesAvailable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_ee3d25153dcd3644, []int{1}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (dst *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(dst, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ServiceList) GetServicesAvailable() []*Service {
	if m != nil {
		return m.ServicesAvailable
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "nan0.Service")
	proto.RegisterType((*ServiceList)(nil), "nan0.ServiceList")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_service_ee3d25153dcd3644) }

var fileDescriptor_service_ee3d25153dcd3644 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x03, 0xf3, 0x84, 0x58, 0xf2, 0x12,
	0xf3, 0x0c, 0x94, 0x0e, 0x33, 0x72, 0xb1, 0x07, 0x43, 0xc4, 0x85, 0x84, 0xb8, 0x58, 0x0a, 0xf2,
	0x8b, 0x4a, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x35, 0x2e, 0xbe, 0x92,
	0xcc, 0xdc, 0xd4, 0x90, 0x7c, 0x9f, 0xcc, 0xb2, 0x54, 0xcf, 0x3c, 0xdf, 0x60, 0x09, 0x26, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0x34, 0x51, 0x21, 0x19, 0x2e, 0xce, 0xe2, 0x92, 0xc4, 0xa2, 0x92, 0x90,
	0xcc, 0xdc, 0x54, 0x09, 0x66, 0xb0, 0x12, 0x84, 0x80, 0x90, 0x14, 0x17, 0x47, 0x46, 0x7e, 0x71,
	0x89, 0x5f, 0x62, 0x6e, 0xaa, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x9c, 0x2f, 0xa4, 0xc0,
	0xc5, 0x0d, 0x75, 0x18, 0x58, 0x9a, 0x15, 0x2c, 0x8d, 0x2c, 0x84, 0xa4, 0x22, 0xa4, 0xb2, 0x20,
	0x55, 0x82, 0x0d, 0x45, 0x05, 0x48, 0x48, 0x29, 0x87, 0x8b, 0x1b, 0xea, 0x09, 0x9f, 0xcc, 0xe2,
	0x12, 0x74, 0x0d, 0x4c, 0x18, 0x1a, 0x84, 0xac, 0xb9, 0x04, 0xa1, 0xdc, 0x62, 0xc7, 0xb2, 0xc4,
	0xcc, 0x9c, 0xc4, 0xa4, 0x1c, 0x90, 0xb3, 0x99, 0x35, 0xb8, 0x8d, 0x78, 0xf5, 0x40, 0x01, 0xa3,
	0x07, 0x35, 0x2f, 0x08, 0x53, 0x9d, 0x13, 0x5b, 0x14, 0x38, 0xec, 0x92, 0xd8, 0xc0, 0x01, 0x69,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xf9, 0x91, 0xf9, 0x5f, 0x01, 0x00, 0x00,
}
