// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/service.proto

package nan0

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Service struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	TimeToLiveInMS       int64    `protobuf:"varint,2,opt,name=timeToLiveInMS,proto3" json:"timeToLiveInMS,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	HostName             string   `protobuf:"bytes,4,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ServiceName          string   `protobuf:"bytes,5,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceType          string   `protobuf:"bytes,6,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8f7301d9b350495, []int{0}
}
func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (dst *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(dst, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Service) GetTimeToLiveInMS() int64 {
	if m != nil {
		return m.TimeToLiveInMS
	}
	return 0
}

func (m *Service) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Service) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

type ServiceList struct {
	ServiceType          string     `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	ServicesAvailable    []*Service `protobuf:"bytes,3,rep,name=servicesAvailable,proto3" json:"servicesAvailable,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceList) Reset()         { *m = ServiceList{} }
func (m *ServiceList) String() string { return proto.CompactTextString(m) }
func (*ServiceList) ProtoMessage()    {}
func (*ServiceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8f7301d9b350495, []int{1}
}
func (m *ServiceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceList.Unmarshal(m, b)
}
func (m *ServiceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceList.Marshal(b, m, deterministic)
}
func (dst *ServiceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceList.Merge(dst, src)
}
func (m *ServiceList) XXX_Size() int {
	return xxx_messageInfo_ServiceList.Size(m)
}
func (m *ServiceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceList.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceList proto.InternalMessageInfo

func (m *ServiceList) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *ServiceList) GetServicesAvailable() []*Service {
	if m != nil {
		return m.ServicesAvailable
	}
	return nil
}

type ServiceMessage struct {
	Data                 *any.Any `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceMessage) Reset()         { *m = ServiceMessage{} }
func (m *ServiceMessage) String() string { return proto.CompactTextString(m) }
func (*ServiceMessage) ProtoMessage()    {}
func (*ServiceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_a8f7301d9b350495, []int{2}
}
func (m *ServiceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceMessage.Unmarshal(m, b)
}
func (m *ServiceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceMessage.Marshal(b, m, deterministic)
}
func (dst *ServiceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceMessage.Merge(dst, src)
}
func (m *ServiceMessage) XXX_Size() int {
	return xxx_messageInfo_ServiceMessage.Size(m)
}
func (m *ServiceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceMessage proto.InternalMessageInfo

func (m *ServiceMessage) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Service)(nil), "nan0.Service")
	proto.RegisterType((*ServiceList)(nil), "nan0.ServiceList")
	proto.RegisterType((*ServiceMessage)(nil), "nan0.ServiceMessage")
}

func init() { proto.RegisterFile("proto/service.proto", fileDescriptor_service_a8f7301d9b350495) }

var fileDescriptor_service_a8f7301d9b350495 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x36, 0x0d, 0xf4, 0x22, 0x2a, 0x61, 0x18, 0x42, 0xc5, 0x10, 0x65, 0x40, 0x99,
	0x1c, 0x54, 0x36, 0x98, 0xca, 0x86, 0xd4, 0x32, 0xa4, 0x99, 0xd8, 0x1c, 0x38, 0x82, 0xa5, 0x24,
	0x8e, 0x62, 0x13, 0x29, 0xbf, 0x8f, 0x3f, 0x86, 0x72, 0x31, 0x50, 0xda, 0xcd, 0xf7, 0xde, 0xf7,
	0xac, 0xf3, 0x33, 0x5c, 0x34, 0xad, 0x32, 0x2a, 0xd1, 0xd8, 0x76, 0xf2, 0x15, 0x39, 0x4d, 0xcc,
	0xad, 0x45, 0x7d, 0xbb, 0xbc, 0x2a, 0x94, 0x2a, 0x4a, 0x4c, 0x48, 0xcb, 0x3f, 0xdf, 0x13, 0x51,
	0xf7, 0x23, 0x10, 0x7d, 0x39, 0x70, 0xb2, 0x1b, 0x23, 0x8c, 0x81, 0xdb, 0xa8, 0xd6, 0x04, 0x4e,
	0xe8, 0xc4, 0xb3, 0x94, 0xce, 0xec, 0x06, 0x16, 0x46, 0x56, 0x98, 0xa9, 0x8d, 0xec, 0xf0, 0xa9,
	0xde, 0xee, 0x82, 0x49, 0xe8, 0xc4, 0xd3, 0xf4, 0x40, 0x65, 0xd7, 0x30, 0xd7, 0x46, 0xb4, 0x26,
	0x93, 0x15, 0x06, 0x53, 0x42, 0xfe, 0x04, 0xb6, 0x84, 0xd3, 0x0f, 0xa5, 0xcd, 0xb3, 0xa8, 0x30,
	0x70, 0x43, 0x27, 0x9e, 0xa7, 0xbf, 0x33, 0x0b, 0xc1, 0xb7, 0x3b, 0x93, 0x3d, 0x23, 0x7b, 0x5f,
	0xda, 0x23, 0xb2, 0xbe, 0xc1, 0xc0, 0xfb, 0x47, 0x0c, 0x52, 0x54, 0x82, 0x6f, 0x1f, 0xb1, 0x91,
	0xda, 0x1c, 0x06, 0x26, 0x47, 0x01, 0xf6, 0x00, 0xe7, 0x76, 0xd4, 0xeb, 0x4e, 0xc8, 0x52, 0xe4,
	0xe5, 0xb0, 0xf6, 0x34, 0xf6, 0x57, 0x67, 0x7c, 0xe8, 0x8c, 0xdb, 0xfb, 0xd2, 0x63, 0x2e, 0xba,
	0x87, 0x85, 0x75, 0xb7, 0xa8, 0xb5, 0x28, 0x90, 0xc5, 0xe0, 0xbe, 0x09, 0x23, 0xa8, 0x39, 0x7f,
	0x75, 0xc9, 0xc7, 0xbe, 0xf9, 0x4f, 0xdf, 0x7c, 0x5d, 0xf7, 0x29, 0x11, 0x8f, 0xde, 0x0b, 0x7d,
	0x49, 0xee, 0x91, 0x77, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xb4, 0x3a, 0x7e, 0xb6, 0x01,
	0x00, 0x00,
}
